name: Build and Deploy to Azure VM

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (Maven)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the Spring Boot app using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Set up SSH and deploy to Azure VM
      - name: Set up SSH and deploy
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the app directory
            mkdir -p /home/${{ secrets.SSH_USERNAME }}/my-springboot-app
            cd /home/${{ secrets.SSH_USERNAME }}/my-springboot-app

            # Copy the built JAR and Dockerfile to the Azure VM
            echo "Copying files to Azure VM..."
            scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:target/*.jar .
            scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:Dockerfile .

            # Stop and remove the existing container (if any)
            docker stop my-springboot-app || true
            docker rm my-springboot-app || true

            # Build the Docker image
            docker build -t my-springboot-app .

            # Run the new container with environment variables
            docker run -d \
              --name my-springboot-app \
              -p 9292:9292 \
              -e MONGO_CONNECTION=${{ secrets.MONGO_CONNECTION }} \
              -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
              -e REDIS_KEY=${{ secrets.REDIS_KEY }} \
              my-springboot-app